adjective1=input("Give me an adjective: ")
noun1=input("Give me a noun: ")
ptVerb1=input("Give me a past tense verb: ")
adverb1=input("Give me an adverb: ")
adjective2=input("Give me an adjective: ")
noun2=input("Give me a noun: ")
noun3=input("Give me a noun: ")
adjective3=input("Give me an adjective: ")
Verb1=input("Give me a verb: ")
adverb2=input("Give me an adverb: ")
ptVerb2=input("Give me a past tense verb: ")
adjective4=input("Give me an adjective: ")
print("Today I went to the zoo. I saw a(n) " + adjective1 , noun1 + " jumping up and down in its tree.")
print("He " + ptVerb1 , adverb1 + " through the large tunnel that led to its " + adjective2 , noun2 + ".")
print("I got some peanuts and passed them through the cage to a gigantic gray " + noun3 + " towering above my head.") 
print("Feeding that animal made me hungry.")
print("I went to get a " + adjective3 + " scoop of ice cream.") 
print("It filled my stomach. Afterwards I had to " + Verb1 , adverb2 + " to catch our bus.")
print("When I got home I " + ptVerb2 + " my mom for a " + adjective4 + " day at the zoo.")

